USE [master]
GO

/****** Object:  Database [SimpleStore]    Script Date: 31/08/2021 15:05:50 ******/
CREATE DATABASE [SimpleStore]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SimpleStore', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SimpleStore.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SimpleStore_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SimpleStore_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SimpleStore].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SimpleStore] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SimpleStore] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SimpleStore] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SimpleStore] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SimpleStore] SET ARITHABORT OFF 
GO

ALTER DATABASE [SimpleStore] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SimpleStore] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SimpleStore] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SimpleStore] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SimpleStore] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SimpleStore] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SimpleStore] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SimpleStore] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SimpleStore] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SimpleStore] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SimpleStore] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SimpleStore] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SimpleStore] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SimpleStore] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SimpleStore] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SimpleStore] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SimpleStore] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SimpleStore] SET RECOVERY FULL 
GO

ALTER DATABASE [SimpleStore] SET  MULTI_USER 
GO

ALTER DATABASE [SimpleStore] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SimpleStore] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SimpleStore] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SimpleStore] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SimpleStore] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SimpleStore] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SimpleStore] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SimpleStore] SET  READ_WRITE 
GO

